language: r
sudo: false
cache: packages
r_github_packages:
- cloudyr/travisci
after_success:
- Rscript -e "travisci::restart_last_build('ropensci/tabulizer')"
env:
  global:
    secure: BoGAp+gBp1BVhoduK5S9dUjB3rrTTZ834qKNHeszP8CXCx3Y6lcHjXU3McQkNEzE30fDhAUzFpyPxp3TEaMrEap2sZHL7EDWF5DUMsny/K/CRBVci/BgFPlPI7MeYgqBE638OXK0Tce2U0336rLRNmrTwWF2KyEFTi9YTuRk+0L/bwgiLXhAm5IYM0g1Ot+uAlAcIowE3XpebmtxS7IGbWSXtnVcVeGinKCsf8GyKefkhFhF2q2p9fWL5cEMYCf0N9TH2coFENk5peUGlUGQVotXH1gIrQgWmzdh2I7FrFcsgZr+GaXcnrB1qbcH5f+T4KbccH1OhTE034PLDS7mzwgbiOW7ZLlkNBxfSn0EeIiqtXwcyiN8qLwJ6qiLayjHhDDyw48rYI6JCGVa53ZmtXbBg0rmnHbXe4Cg7KNXPY+2v71er7ukCkqGudCFPHbxwQ2BmR9S1uj4xjO0p1A7VwRKh/TSNTyfZsqwjVk6kPPbLCEEXH6s71NnE+6ttKo8pBwMeoBH+MJ4x8btbV2tYDa9dt39u6/FkyUcxrtUHaL9niFZprS3cLlgdA9yEt2Ul7FIGXsIpp9lKcX/yPTtKv7NE3WCX9wlCNwzw58kPHF1vYzedm9cAyNoN8SVBc98gqZadA/bkHYrurjRABIfKxuRIgGAGCBUjJ1TEMLtTNo=
